---
title: "DataPrep.Rmd"
author: "Jawaid Hakim"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readtext)
library(stringi)
library(textclean)
```

```{r}
easy_ham_folders <- c('./ham_spam_dataset/easy_ham/', './ham_spam_dataset/easy_ham 2/', './ham_spam_dataset/easy_ham_2/')
hard_ham_folders <- c('./ham_spam_dataset/hard_ham/', './ham_spam_dataset/hard_ham 2/')

all_ham_folders <- easy_ham_folders
all_ham_folders <- append(all_ham_folders, hard_ham_folders)

spam_folders <- c('./ham_spam_dataset/spam/', './ham_spam_dataset/spam 2/', './ham_spam_dataset/spam_2/', './ham_spam_dataset/spam_2 2')

```

```{r}
library(stringi)

ReadAndCleanEmail <- function(path) {
        print(path)
        
        con <- file(path, encoding = 'UTF-8')
        lines <- readLines(con, skipNul = TRUE)
        close(con = con)
        
        skip <- TRUE
        filtered <- ' '
        from <- ''
        subject <- ''
        for (l in lines) {
            if (skip)
            {
                if (str_length(l) > 0)
                {
                    lc = str_trim(str_to_lower(l), "left")
                    if (str_length(subject) == 0 && str_starts(lc, "subject:")) {
                        lc = str_remove(lc, "subject:")
                        subject = str_squish(lc)
                    }
                    else if (str_length(from) == 0 && str_starts(lc, "from:")) {
                        lc = str_remove(lc, "from:")
                        from = str_squish(lc)
                    }
                }
                else
                {
                    skip = FALSE
                }
            } else if (! skip) {
                filtered <- paste0(filtered, stri_enc_toascii(l))
                #print(paste0("***: ", skip, ", ", l))
            }
        }
        return(list(from = from, subject = subject, text = filtered))
}

ReadEmails <- function(folders, category) {
    result <- tibble(from = c(''), subject = c(''), email_src = c(''), category = (''), text = c(''))
    for (folder in folders) {
        file_list <- dir(path = folder)
        for (f in file_list) {
            #if (str_starts(email_file, "0001\\.ea7e79d")) {
            path <- paste0(folder, .Platform$file.sep, f)
            email  <- ReadAndCleanEmail(path)
            if (str_length(email$from) > 0) {
                result <- result %>% add_row(from = email$from, subject = email$subject, email_src = path, category = category, text = email$text)
            }
            #} #
        }
    }
    return (result)
}
```


```{r}
easy_hams <- ReadEmails(easy_ham_folders, category = 'ham')
#hard_hams <- ReadEmails(hard_ham_folders, category = 'ham')
spams <- ReadEmails(spam_folders, category = 'spam')
```

```{r}
sms <- bind_rows(spams, easy_hams)
```

```{r}
write.csv(sms, file = "EMAILSpamCollection.csv", quote = TRUE)
```

