---
title: "Assignment9 - Web APIs"
author: "Jawaid Hakim"
date: "`r Sys.Date()`"
output:
  
  html_document:
    
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
  pdf_document: 
    toc: true
    toc_depth: 3
    number_sections: true
boxlinks: true
urlcolor: blue
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

# Load libraries

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(jsonlite)
library(lubridate)
```

# Assignment
    
# Search terms
```{r}
nytSearchFunc <- function(api_name, search_terms = "", page = 1, begin_date = format(Sys.Date(), "%Y%m%d"), end_date = format(Sys.Date(), "%Y%m%d")){
                        baseurl <- "https://api.nytimes.com/svc/search/v2/articlesearch.json?"
                        if (!is_empty(search_terms)) {
                            baseurl <- paste0(baseurl, search_terms, "&")
                        }
                        baseurl <- paste0(baseurl,
                                    "begin_date=", begin_date,
                                    "&end_date=", end_date,
                                    "&page=", page,
                                    "&api-key=","2mGra8XCfEhUdE4WxThgvyCs55BZLfLK", 
                                    sep="")
                         fromJSON(baseurl)
                }
```

```{r}
res <- nytSearchFunc("foo", page = 1)
```


```{r}
              )
x <- fromJSON("https://api.nytimes.com/svc/mostpopular/v2/viewed/7.json?api-key=2mGra8XCfEhUdE4WxThgvyCs55BZLfLK", flatten = TRUE) %>% data.frame()

```

```{r}
```

