-- MySQL Script generated by MySQL Workbench
-- Wed Sep  7 15:37:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Assignment - SQL and R
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Assignment - SQL and R
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Assignment - SQL and R` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Assignment - SQL and R` ;

-- -----------------------------------------------------
-- Table `Assignment - SQL and R`.`FRIENDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment - SQL and R`.`FRIENDS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

ALTER TABLE `Assignment - SQL and R`.`FRIENDS` AUTO_INCREMENT=1;

-- -----------------------------------------------------
-- Table `Assignment - SQL and R`.`MOVIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment - SQL and R`.`MOVIES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

ALTER TABLE `Assignment - SQL and R`.`MOVIES` AUTO_INCREMENT=1;

-- -----------------------------------------------------
-- Table `Assignment - SQL and R`.`RATINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment - SQL and R`.`RATINGS` (
  `FRIEND_ID` INT NOT NULL,
  `MOVIE_ID` INT NOT NULL,
  `RATING` ENUM('0', '1', '2', '3', '4', '5') NOT NULL DEFAULT '0',
  INDEX `FRIEND_ID_idx` (`FRIEND_ID` ASC) VISIBLE,
  INDEX `MOVIE_ID_idx` (`MOVIE_ID` ASC) VISIBLE,
  CONSTRAINT `FRIEND_ID`
    FOREIGN KEY (`FRIEND_ID`)
    REFERENCES `Assignment - SQL and R`.`FRIENDS` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `MOVIE_ID`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `Assignment - SQL and R`.`MOVIES` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER IF NOT EXISTS `guest`@`localhost` 
	IDENTIFIED BY 'guestpass';
GRANT DELETE, EXECUTE, INSERT, SELECT, SHOW VIEW, UPDATE ON `Assignment - SQL and R`.* TO `guest`@`localhost`;

